// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coin.proto

package io.streams;

public final class CoinOuterClass {
  private CoinOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CoinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.streams.Coin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string maker_order_id = 2;</code>
     * @return Whether the makerOrderId field is set.
     */
    boolean hasMakerOrderId();
    /**
     * <code>optional string maker_order_id = 2;</code>
     * @return The makerOrderId.
     */
    java.lang.String getMakerOrderId();
    /**
     * <code>optional string maker_order_id = 2;</code>
     * @return The bytes for makerOrderId.
     */
    com.google.protobuf.ByteString
        getMakerOrderIdBytes();

    /**
     * <code>optional string taker_order_id = 3;</code>
     * @return Whether the takerOrderId field is set.
     */
    boolean hasTakerOrderId();
    /**
     * <code>optional string taker_order_id = 3;</code>
     * @return The takerOrderId.
     */
    java.lang.String getTakerOrderId();
    /**
     * <code>optional string taker_order_id = 3;</code>
     * @return The bytes for takerOrderId.
     */
    com.google.protobuf.ByteString
        getTakerOrderIdBytes();

    /**
     * <code>optional string side = 4;</code>
     * @return Whether the side field is set.
     */
    boolean hasSide();
    /**
     * <code>optional string side = 4;</code>
     * @return The side.
     */
    java.lang.String getSide();
    /**
     * <code>optional string side = 4;</code>
     * @return The bytes for side.
     */
    com.google.protobuf.ByteString
        getSideBytes();

    /**
     * <code>optional string product_id = 7;</code>
     * @return Whether the productId field is set.
     */
    boolean hasProductId();
    /**
     * <code>optional string product_id = 7;</code>
     * @return The productId.
     */
    java.lang.String getProductId();
    /**
     * <code>optional string product_id = 7;</code>
     * @return The bytes for productId.
     */
    com.google.protobuf.ByteString
        getProductIdBytes();

    /**
     * <code>optional double size = 1;</code>
     * @return Whether the size field is set.
     */
    boolean hasSize();
    /**
     * <code>optional double size = 1;</code>
     * @return The size.
     */
    double getSize();

    /**
     * <code>optional double price = 6;</code>
     * @return Whether the price field is set.
     */
    boolean hasPrice();
    /**
     * <code>optional double price = 6;</code>
     * @return The price.
     */
    double getPrice();

    /**
     * <code>optional .google.protobuf.Timestamp time = 5;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>optional .google.protobuf.Timestamp time = 5;</code>
     * @return The time.
     */
    com.google.protobuf.Timestamp getTime();
    /**
     * <code>optional .google.protobuf.Timestamp time = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();

    /**
     * <code>optional double trade_id = 8;</code>
     * @return Whether the tradeId field is set.
     */
    boolean hasTradeId();
    /**
     * <code>optional double trade_id = 8;</code>
     * @return The tradeId.
     */
    double getTradeId();
  }
  /**
   * Protobuf type {@code io.streams.Coin}
   */
  public static final class Coin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.streams.Coin)
      CoinOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Coin.newBuilder() to construct.
    private Coin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Coin() {
      makerOrderId_ = "";
      takerOrderId_ = "";
      side_ = "";
      productId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Coin();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.streams.CoinOuterClass.internal_static_io_streams_Coin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.streams.CoinOuterClass.internal_static_io_streams_Coin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.streams.CoinOuterClass.Coin.class, io.streams.CoinOuterClass.Coin.Builder.class);
    }

    private int bitField0_;
    public static final int MAKER_ORDER_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object makerOrderId_ = "";
    /**
     * <code>optional string maker_order_id = 2;</code>
     * @return Whether the makerOrderId field is set.
     */
    @java.lang.Override
    public boolean hasMakerOrderId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string maker_order_id = 2;</code>
     * @return The makerOrderId.
     */
    @java.lang.Override
    public java.lang.String getMakerOrderId() {
      java.lang.Object ref = makerOrderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        makerOrderId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string maker_order_id = 2;</code>
     * @return The bytes for makerOrderId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMakerOrderIdBytes() {
      java.lang.Object ref = makerOrderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        makerOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAKER_ORDER_ID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object takerOrderId_ = "";
    /**
     * <code>optional string taker_order_id = 3;</code>
     * @return Whether the takerOrderId field is set.
     */
    @java.lang.Override
    public boolean hasTakerOrderId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string taker_order_id = 3;</code>
     * @return The takerOrderId.
     */
    @java.lang.Override
    public java.lang.String getTakerOrderId() {
      java.lang.Object ref = takerOrderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        takerOrderId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string taker_order_id = 3;</code>
     * @return The bytes for takerOrderId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTakerOrderIdBytes() {
      java.lang.Object ref = takerOrderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        takerOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIDE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object side_ = "";
    /**
     * <code>optional string side = 4;</code>
     * @return Whether the side field is set.
     */
    @java.lang.Override
    public boolean hasSide() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string side = 4;</code>
     * @return The side.
     */
    @java.lang.Override
    public java.lang.String getSide() {
      java.lang.Object ref = side_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        side_ = s;
        return s;
      }
    }
    /**
     * <code>optional string side = 4;</code>
     * @return The bytes for side.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSideBytes() {
      java.lang.Object ref = side_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        side_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCT_ID_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object productId_ = "";
    /**
     * <code>optional string product_id = 7;</code>
     * @return Whether the productId field is set.
     */
    @java.lang.Override
    public boolean hasProductId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string product_id = 7;</code>
     * @return The productId.
     */
    @java.lang.Override
    public java.lang.String getProductId() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string product_id = 7;</code>
     * @return The bytes for productId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProductIdBytes() {
      java.lang.Object ref = productId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 1;
    private double size_ = 0D;
    /**
     * <code>optional double size = 1;</code>
     * @return Whether the size field is set.
     */
    @java.lang.Override
    public boolean hasSize() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional double size = 1;</code>
     * @return The size.
     */
    @java.lang.Override
    public double getSize() {
      return size_;
    }

    public static final int PRICE_FIELD_NUMBER = 6;
    private double price_ = 0D;
    /**
     * <code>optional double price = 6;</code>
     * @return Whether the price field is set.
     */
    @java.lang.Override
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional double price = 6;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }

    public static final int TIME_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp time_;
    /**
     * <code>optional .google.protobuf.Timestamp time = 5;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp time = 5;</code>
     * @return The time.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTime() {
      return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp time = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
      return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
    }

    public static final int TRADE_ID_FIELD_NUMBER = 8;
    private double tradeId_ = 0D;
    /**
     * <code>optional double trade_id = 8;</code>
     * @return Whether the tradeId field is set.
     */
    @java.lang.Override
    public boolean hasTradeId() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional double trade_id = 8;</code>
     * @return The tradeId.
     */
    @java.lang.Override
    public double getTradeId() {
      return tradeId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeDouble(1, size_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, makerOrderId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, takerOrderId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, side_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeMessage(5, getTime());
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeDouble(6, price_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, productId_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeDouble(8, tradeId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, size_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, makerOrderId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, takerOrderId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, side_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getTime());
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, price_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, productId_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, tradeId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.streams.CoinOuterClass.Coin)) {
        return super.equals(obj);
      }
      io.streams.CoinOuterClass.Coin other = (io.streams.CoinOuterClass.Coin) obj;

      if (hasMakerOrderId() != other.hasMakerOrderId()) return false;
      if (hasMakerOrderId()) {
        if (!getMakerOrderId()
            .equals(other.getMakerOrderId())) return false;
      }
      if (hasTakerOrderId() != other.hasTakerOrderId()) return false;
      if (hasTakerOrderId()) {
        if (!getTakerOrderId()
            .equals(other.getTakerOrderId())) return false;
      }
      if (hasSide() != other.hasSide()) return false;
      if (hasSide()) {
        if (!getSide()
            .equals(other.getSide())) return false;
      }
      if (hasProductId() != other.hasProductId()) return false;
      if (hasProductId()) {
        if (!getProductId()
            .equals(other.getProductId())) return false;
      }
      if (hasSize() != other.hasSize()) return false;
      if (hasSize()) {
        if (java.lang.Double.doubleToLongBits(getSize())
            != java.lang.Double.doubleToLongBits(
                other.getSize())) return false;
      }
      if (hasPrice() != other.hasPrice()) return false;
      if (hasPrice()) {
        if (java.lang.Double.doubleToLongBits(getPrice())
            != java.lang.Double.doubleToLongBits(
                other.getPrice())) return false;
      }
      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (!getTime()
            .equals(other.getTime())) return false;
      }
      if (hasTradeId() != other.hasTradeId()) return false;
      if (hasTradeId()) {
        if (java.lang.Double.doubleToLongBits(getTradeId())
            != java.lang.Double.doubleToLongBits(
                other.getTradeId())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMakerOrderId()) {
        hash = (37 * hash) + MAKER_ORDER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMakerOrderId().hashCode();
      }
      if (hasTakerOrderId()) {
        hash = (37 * hash) + TAKER_ORDER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getTakerOrderId().hashCode();
      }
      if (hasSide()) {
        hash = (37 * hash) + SIDE_FIELD_NUMBER;
        hash = (53 * hash) + getSide().hashCode();
      }
      if (hasProductId()) {
        hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
        hash = (53 * hash) + getProductId().hashCode();
      }
      if (hasSize()) {
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getSize()));
      }
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getPrice()));
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      if (hasTradeId()) {
        hash = (37 * hash) + TRADE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getTradeId()));
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.streams.CoinOuterClass.Coin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.streams.CoinOuterClass.Coin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.streams.CoinOuterClass.Coin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.streams.CoinOuterClass.Coin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.streams.CoinOuterClass.Coin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.streams.CoinOuterClass.Coin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.streams.CoinOuterClass.Coin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.streams.CoinOuterClass.Coin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.streams.CoinOuterClass.Coin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.streams.CoinOuterClass.Coin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.streams.CoinOuterClass.Coin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.streams.CoinOuterClass.Coin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.streams.CoinOuterClass.Coin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.streams.Coin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.streams.Coin)
        io.streams.CoinOuterClass.CoinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.streams.CoinOuterClass.internal_static_io_streams_Coin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.streams.CoinOuterClass.internal_static_io_streams_Coin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.streams.CoinOuterClass.Coin.class, io.streams.CoinOuterClass.Coin.Builder.class);
      }

      // Construct using io.streams.CoinOuterClass.Coin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTimeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        makerOrderId_ = "";
        takerOrderId_ = "";
        side_ = "";
        productId_ = "";
        size_ = 0D;
        price_ = 0D;
        time_ = null;
        if (timeBuilder_ != null) {
          timeBuilder_.dispose();
          timeBuilder_ = null;
        }
        tradeId_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.streams.CoinOuterClass.internal_static_io_streams_Coin_descriptor;
      }

      @java.lang.Override
      public io.streams.CoinOuterClass.Coin getDefaultInstanceForType() {
        return io.streams.CoinOuterClass.Coin.getDefaultInstance();
      }

      @java.lang.Override
      public io.streams.CoinOuterClass.Coin build() {
        io.streams.CoinOuterClass.Coin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.streams.CoinOuterClass.Coin buildPartial() {
        io.streams.CoinOuterClass.Coin result = new io.streams.CoinOuterClass.Coin(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.streams.CoinOuterClass.Coin result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.makerOrderId_ = makerOrderId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.takerOrderId_ = takerOrderId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.side_ = side_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.productId_ = productId_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.size_ = size_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.price_ = price_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.time_ = timeBuilder_ == null
              ? time_
              : timeBuilder_.build();
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.tradeId_ = tradeId_;
          to_bitField0_ |= 0x00000080;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.streams.CoinOuterClass.Coin) {
          return mergeFrom((io.streams.CoinOuterClass.Coin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.streams.CoinOuterClass.Coin other) {
        if (other == io.streams.CoinOuterClass.Coin.getDefaultInstance()) return this;
        if (other.hasMakerOrderId()) {
          makerOrderId_ = other.makerOrderId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasTakerOrderId()) {
          takerOrderId_ = other.takerOrderId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasSide()) {
          side_ = other.side_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasProductId()) {
          productId_ = other.productId_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        if (other.hasTradeId()) {
          setTradeId(other.getTradeId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                size_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 9
              case 18: {
                makerOrderId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 18
              case 26: {
                takerOrderId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 26
              case 34: {
                side_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 42
              case 49: {
                price_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 49
              case 58: {
                productId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 58
              case 65: {
                tradeId_ = input.readDouble();
                bitField0_ |= 0x00000080;
                break;
              } // case 65
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object makerOrderId_ = "";
      /**
       * <code>optional string maker_order_id = 2;</code>
       * @return Whether the makerOrderId field is set.
       */
      public boolean hasMakerOrderId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string maker_order_id = 2;</code>
       * @return The makerOrderId.
       */
      public java.lang.String getMakerOrderId() {
        java.lang.Object ref = makerOrderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          makerOrderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string maker_order_id = 2;</code>
       * @return The bytes for makerOrderId.
       */
      public com.google.protobuf.ByteString
          getMakerOrderIdBytes() {
        java.lang.Object ref = makerOrderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          makerOrderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string maker_order_id = 2;</code>
       * @param value The makerOrderId to set.
       * @return This builder for chaining.
       */
      public Builder setMakerOrderId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        makerOrderId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string maker_order_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMakerOrderId() {
        makerOrderId_ = getDefaultInstance().getMakerOrderId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string maker_order_id = 2;</code>
       * @param value The bytes for makerOrderId to set.
       * @return This builder for chaining.
       */
      public Builder setMakerOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        makerOrderId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object takerOrderId_ = "";
      /**
       * <code>optional string taker_order_id = 3;</code>
       * @return Whether the takerOrderId field is set.
       */
      public boolean hasTakerOrderId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string taker_order_id = 3;</code>
       * @return The takerOrderId.
       */
      public java.lang.String getTakerOrderId() {
        java.lang.Object ref = takerOrderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          takerOrderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string taker_order_id = 3;</code>
       * @return The bytes for takerOrderId.
       */
      public com.google.protobuf.ByteString
          getTakerOrderIdBytes() {
        java.lang.Object ref = takerOrderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          takerOrderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string taker_order_id = 3;</code>
       * @param value The takerOrderId to set.
       * @return This builder for chaining.
       */
      public Builder setTakerOrderId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        takerOrderId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string taker_order_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTakerOrderId() {
        takerOrderId_ = getDefaultInstance().getTakerOrderId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string taker_order_id = 3;</code>
       * @param value The bytes for takerOrderId to set.
       * @return This builder for chaining.
       */
      public Builder setTakerOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        takerOrderId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object side_ = "";
      /**
       * <code>optional string side = 4;</code>
       * @return Whether the side field is set.
       */
      public boolean hasSide() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string side = 4;</code>
       * @return The side.
       */
      public java.lang.String getSide() {
        java.lang.Object ref = side_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          side_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string side = 4;</code>
       * @return The bytes for side.
       */
      public com.google.protobuf.ByteString
          getSideBytes() {
        java.lang.Object ref = side_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          side_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string side = 4;</code>
       * @param value The side to set.
       * @return This builder for chaining.
       */
      public Builder setSide(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        side_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string side = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSide() {
        side_ = getDefaultInstance().getSide();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string side = 4;</code>
       * @param value The bytes for side to set.
       * @return This builder for chaining.
       */
      public Builder setSideBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        side_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object productId_ = "";
      /**
       * <code>optional string product_id = 7;</code>
       * @return Whether the productId field is set.
       */
      public boolean hasProductId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string product_id = 7;</code>
       * @return The productId.
       */
      public java.lang.String getProductId() {
        java.lang.Object ref = productId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string product_id = 7;</code>
       * @return The bytes for productId.
       */
      public com.google.protobuf.ByteString
          getProductIdBytes() {
        java.lang.Object ref = productId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string product_id = 7;</code>
       * @param value The productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        productId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string product_id = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductId() {
        productId_ = getDefaultInstance().getProductId();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string product_id = 7;</code>
       * @param value The bytes for productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        productId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private double size_ ;
      /**
       * <code>optional double size = 1;</code>
       * @return Whether the size field is set.
       */
      @java.lang.Override
      public boolean hasSize() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional double size = 1;</code>
       * @return The size.
       */
      @java.lang.Override
      public double getSize() {
        return size_;
      }
      /**
       * <code>optional double size = 1;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(double value) {
        
        size_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional double size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        size_ = 0D;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>optional double price = 6;</code>
       * @return Whether the price field is set.
       */
      @java.lang.Override
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional double price = 6;</code>
       * @return The price.
       */
      @java.lang.Override
      public double getPrice() {
        return price_;
      }
      /**
       * <code>optional double price = 6;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional double price = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000020);
        price_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp time_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp time = 5;</code>
       * @return Whether the time field is set.
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional .google.protobuf.Timestamp time = 5;</code>
       * @return The time.
       */
      public com.google.protobuf.Timestamp getTime() {
        if (timeBuilder_ == null) {
          return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp time = 5;</code>
       */
      public Builder setTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
        } else {
          timeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp time = 5;</code>
       */
      public Builder setTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp time = 5;</code>
       */
      public Builder mergeTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            time_ != null &&
            time_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getTimeBuilder().mergeFrom(value);
          } else {
            time_ = value;
          }
        } else {
          timeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp time = 5;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        time_ = null;
        if (timeBuilder_ != null) {
          timeBuilder_.dispose();
          timeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp time = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimeBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp time = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp time = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }

      private double tradeId_ ;
      /**
       * <code>optional double trade_id = 8;</code>
       * @return Whether the tradeId field is set.
       */
      @java.lang.Override
      public boolean hasTradeId() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional double trade_id = 8;</code>
       * @return The tradeId.
       */
      @java.lang.Override
      public double getTradeId() {
        return tradeId_;
      }
      /**
       * <code>optional double trade_id = 8;</code>
       * @param value The tradeId to set.
       * @return This builder for chaining.
       */
      public Builder setTradeId(double value) {
        
        tradeId_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional double trade_id = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTradeId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        tradeId_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.streams.Coin)
    }

    // @@protoc_insertion_point(class_scope:io.streams.Coin)
    private static final io.streams.CoinOuterClass.Coin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.streams.CoinOuterClass.Coin();
    }

    public static io.streams.CoinOuterClass.Coin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Coin>
        PARSER = new com.google.protobuf.AbstractParser<Coin>() {
      @java.lang.Override
      public Coin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Coin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Coin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.streams.CoinOuterClass.Coin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_streams_Coin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_streams_Coin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncoin.proto\022\nio.streams\032\037google/protobu" +
      "f/timestamp.proto\"\300\002\n\004Coin\022\033\n\016maker_orde" +
      "r_id\030\002 \001(\tH\000\210\001\001\022\033\n\016taker_order_id\030\003 \001(\tH" +
      "\001\210\001\001\022\021\n\004side\030\004 \001(\tH\002\210\001\001\022\027\n\nproduct_id\030\007 " +
      "\001(\tH\003\210\001\001\022\021\n\004size\030\001 \001(\001H\004\210\001\001\022\022\n\005price\030\006 \001" +
      "(\001H\005\210\001\001\022-\n\004time\030\005 \001(\0132\032.google.protobuf." +
      "TimestampH\006\210\001\001\022\025\n\010trade_id\030\010 \001(\001H\007\210\001\001B\021\n" +
      "\017_maker_order_idB\021\n\017_taker_order_idB\007\n\005_" +
      "sideB\r\n\013_product_idB\007\n\005_sizeB\010\n\006_priceB\007" +
      "\n\005_timeB\013\n\t_trade_idb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_io_streams_Coin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_streams_Coin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_streams_Coin_descriptor,
        new java.lang.String[] { "MakerOrderId", "TakerOrderId", "Side", "ProductId", "Size", "Price", "Time", "TradeId", "MakerOrderId", "TakerOrderId", "Side", "ProductId", "Size", "Price", "Time", "TradeId", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
